import { describe, expect, it } from "vitest";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { buildAdminEmail, buildCustomerEmail } from "../diagnosticEmails";
import { base, injection, long, manualScope, sparse } from "./fixtures";

/**
 * Local previews of both emails, written to `email-previews/`, and the
 * checks that go with them.
 *
 * Generated by the same modules that send, so a preview cannot drift from
 * what would actually go out — which a separate preview script, or a
 * hand-written sample, eventually would. Open `email-previews/index.html`.
 *
 * Fictional data only. Nothing here touches the database, the mail
 * provider or any real submission.
 */

const OUT = path.join(process.cwd(), "email-previews");
/*
 * The previews are rendered with the PRODUCTION origin, so every link,
 * the signature and the footer read exactly as they will when sent.
 *
 * The header image is not published there yet, so opening a preview
 * straight from disk shows the blocked-image fallback — which is the
 * diagnosis of "the header looks wrong", not a fault in the header:
 * `/brand/email-header-v1.jpg` 404s on the live site until this deploys,
 * and serves 200 locally. `emailPreviewShots.spec.ts` serves that one URL
 * from `public/` when photographing the loaded state, which keeps the
 * HTML itself honest.
 */
const ORIGIN = process.env.MODUS_EMAIL_PREVIEW_ORIGIN ?? "https://www.withmodus.co";
const PRODUCTION_ORIGIN = "https://www.withmodus.co";

const cases = [
  ["01-customer-nl", () => buildCustomerEmail(base, "nl", ORIGIN)],
  ["02-customer-en", () => buildCustomerEmail(base, "en", ORIGIN)],
  // The chosen customer layout, in both languages. Everything authored is
  // translated — subject, preheader, greeting, body, sign-off, footer —
  // while the name, the company and their own words stay exactly as
  // written.
  ["03-customer-nl-long", () => buildCustomerEmail(long, "nl", ORIGIN)],
  ["03-customer-en-long", () => buildCustomerEmail(long, "en", ORIGIN)],
  ["04-customer-nl-sparse", () => buildCustomerEmail(sparse, "nl", ORIGIN)],
  ["05-customer-en-sparse", () => buildCustomerEmail(sparse, "en", ORIGIN)],
  ["06-customer-nl-priority-from-list", () => buildCustomerEmail(manualScope, "nl", ORIGIN)],
  ["07-customer-nl-escaping", () => buildCustomerEmail(injection, "nl", ORIGIN)],
  ["08-admin", () => buildAdminEmail(base, ORIGIN)],
  ["09-admin-long", () => buildAdminEmail(long, ORIGIN)],
  ["10-admin-sparse", () => buildAdminEmail(sparse, ORIGIN)],
  ["11-admin-manual-scope", () => buildAdminEmail(manualScope, ORIGIN)],
  ["12-admin-escaping", () => buildAdminEmail(injection, ORIGIN)],
] as const;

describe("previews", () => {
  it("writes an HTML and a text file per case, plus an index", () => {
    mkdirSync(OUT, { recursive: true });
    const rows: string[] = [];

    for (const [name, build] of cases) {
      const mail = build();
      writeFileSync(path.join(OUT, `${name}.html`), mail.html, "utf8");
      writeFileSync(path.join(OUT, `${name}.txt`), mail.text, "utf8");
      // Both parts exist for every case: a message with no text part is
      // unreadable in a text client and scores worse with spam filters.
      expect(mail.html.length, `${name} html`).toBeGreaterThan(400);
      expect(mail.text.trim().length, `${name} text`).toBeGreaterThan(40);
      rows.push(
        `<li><a href="${name}.html">${name}</a> &middot; <a href="${name}.txt">text</a>` +
          `<br /><small>${mail.subject.replace(/&/g, "&amp;").replace(/</g, "&lt;")}` +
          ` &middot; reply-to ${mail.replyTo}</small></li>`
      );
    }

    writeFileSync(
      path.join(OUT, "index.html"),
      `<!doctype html><meta charset="utf-8"><title>MODUS email previews</title>` +
        `<body style="font-family:system-ui;max-width:48rem;margin:3rem auto;line-height:1.7">` +
        `<h1>MODUS email previews</h1>` +
        `<p>Fictional data. Rendered by the same modules that send.</p>` +
        `<ul>${rows.join("")}</ul></body>`,
      "utf8"
    );
  });

  it("is email-shaped HTML, not web HTML", () => {
    const { html } = buildCustomerEmail(base, "nl", ORIGIN);
    // Width as an attribute, so a client that drops the <style> still
    // renders the layout.
    expect(html).toContain('width="600"');
    expect(html).toContain('role="presentation"');
    expect(html).toContain("<!doctype html>");
    // The header is absolute and versioned: mail clients and their image
    // proxies cache by URL.
    expect(html).toContain(`${ORIGIN}/brand/email-header-v1.jpg`);
    // And with the real origin it is the real absolute URL, whatever the
    // preview default happens to be.
    expect(buildCustomerEmail(base, "nl", PRODUCTION_ORIGIN).html).toContain(
      "https://www.withmodus.co/brand/email-header-v1.jpg"
    );
    expect(html).toContain('alt="MODUS"');
    // Scales down rather than forcing a 600px viewport on a phone, and is
    // never cropped or stretched: no fixed container height, no
    // object-fit, no overflow clipping.
    expect(html).toContain("max-width:600px");
    expect(html).toContain("height:auto");
    // Scoped to the image: `overflow:hidden` legitimately appears on the
    // hidden preheader, which is a different element doing a different job.
    const img = html.match(/<img[^>]*>/)![0];
    expect(img).not.toContain("object-fit");
    expect(img).not.toContain("overflow");
    // The attribute pair matches the asset's own 3:1 ratio, for clients
    // that size from attributes rather than styles.
    expect(html).toMatch(/<img[^>]*width="600"[^>]*height="200"/);
    // No external stylesheet, script or font: those do not survive an
    // inbox, and a mail that needs them is a mail that breaks.
    expect(html).not.toContain("<link");
    expect(html).not.toContain("<script");
  });

  it("still reads as MODUS when images are blocked", () => {
    // A great many people read mail with images off, and every image
    // proxy fails sometimes. Unstyled, the header would be 200 pixels of
    // nothing above the first word.
    const { html } = buildCustomerEmail(base, "nl", ORIGIN);
    expect(html).toContain('bgcolor="#1E3B2E"');
    expect(html).toMatch(/<img[^>]*alt="MODUS"[^>]*color:#FFFFFF/);
    // Left aligned, so a blocked header echoes the real one rather than
    // reading as centred text that replaced the artwork.
    expect(html).toMatch(/<img[^>]*text-align:left/);
    expect(html).not.toMatch(/<img[^>]*text-align:center/);
  });

  it("carries one logo, not two", () => {
    // The header image is the brand mark. A second wordmark in the footer
    // would be the same logo twice in 600 pixels.
    const { html } = buildCustomerEmail(base, "nl", ORIGIN);
    expect(html.match(/<img/g) ?? []).toHaveLength(1);
  });
});
